/**
 * Persian (Farsi) translations for Nexus.
 * Use: fa.common.signIn, fa.dashboard.todayBalance, etc.
 */
export const fa = {
  common: {
    signIn: 'ورود',
    signOut: 'خروج',
    createAccount: 'ایجاد حساب',
    save: 'ذخیره',
    cancel: 'انصراف',
    close: 'بستن',
    retry: 'تلاش مجدد',
    loading: 'در حال بارگذاری…',
    edit: 'ویرایش',
    delete: 'حذف',
    deleting: 'در حال حذف…',
    viewAll: 'مشاهده همه',
    export: 'خروجی',
    print: 'چاپ',
    skipToContent: 'پرش به محتوای اصلی',
    guest: 'مهمان',
    settings: 'تنظیمات',
    notFound: 'یافت نشد',
    error: 'خطا',
    success: 'موفق',
  },
  nav: {
    overview: 'نمای کلی',
    runway: 'مدت دوام',
    revenue: 'درآمد',
    expenses: 'هزینه‌ها',
    reports: 'گزارش‌ها',
    investors: 'سرمایه‌گذاران',
    automations: 'اتوماسیون',
    accounts: 'حساب‌ها',
    payments: 'پرداخت‌ها',
    junior: 'جونیور',
    banking: 'بانکی',
    linkBank: 'اتصال بانک',
    recurring: 'تکرارشونده',
    budgets: 'بودجه‌ها',
    goals: 'اهداف',
    transactions: 'تراکنش‌ها',
    profile: 'پروفایل',
    editProfile: 'ویرایش پروفایل',
    appearance: 'ظاهر',
    notifications: 'اعلان‌ها',
    noNewAlerts: 'اعلان جدیدی نیست',
    viewAllBudgets: 'مشاهده همه بودجه‌ها',
  },
  auth: {
    signInToNexus: 'ورود به نکسوس',
    username: 'نام کاربری',
    password: 'رمز عبور',
    forgotPassword: 'رمز عبور را فراموش کرده‌اید؟',
    signingIn: 'در حال ورود…',
    dontHaveAccount: 'حساب کاربری ندارید؟ ثبت‌نام',
    createYourAccount: 'ایجاد حساب نکسوس',
    email: 'ایمیل',
    fullName: 'نام کامل',
    register: 'ثبت‌نام',
    creatingAccount: 'در حال ایجاد حساب…',
    alreadyHaveAccount: 'قبلاً حساب دارید؟ ورود',
    loginFailed: 'ورود ناموفق',
    registrationFailed: 'ثبت‌نام ناموفق',
    resetPassword: 'بازنشانی رمز عبور',
    forgotPasswordTitle: 'فراموشی رمز عبور',
    sendResetLink: 'ارسال لینک بازنشانی',
    newPassword: 'رمز عبور جدید',
    confirmPassword: 'تأیید رمز عبور',
    backToSignIn: 'بازگشت به ورود',
    checkYourEmail: 'ایمیل خود را بررسی کنید',
    resetEmailMessage: 'اگر حسابی با این ایمیل وجود داشته باشد، دستورالعمل بازنشانی را دریافت خواهید کرد. در حالت توسعه، لینک در کنسول سرور لاگ می‌شود.',
    enterEmailReset: 'ایمیل خود را وارد کنید تا لینک بازنشانی رمز عبور را بفرستیم.',
    sending: 'در حال ارسال…',
  },
  dashboard: {
    titleBeforeRealtime: 'داده‌های نقد، سوخت و مدت دوام را به‌صورت ',
    realtime: 'لحظه‌ای',
    titleAfterRealtime: ' ببینید.',
    title: 'داده‌های نقد، سوخت و مدت دوام را به‌صورت لحظه‌ای ببینید.',
    founderOverview: 'نمای کلی بنیانگذار — هوش مالی لحظه‌ای.',
    investorMode: 'حالت سرمایه‌گذار',
    todayBalance: 'موجودی امروز',
    operatingBurn: 'سوخت عملیاتی',
    runwayRunRate: 'مدت دوام',
    months: 'ماه',
    mrr: 'درآمد ماهانه تکرارشونده',
    arr: 'درآمد سالانه تکرارشونده',
    revenueGrowth: 'رشد درآمد',
    cashIn30d: 'ورود نقدی (۳۰ روز)',
    cashOut30d: 'خروج نقدی (۳۰ روز)',
    charts: 'نمودارها',
    netBurnAndCash: 'سوخت خالص و موجودی نقد',
    spending: 'هزینه',
    revenue: 'درآمد',
    burnIntelligence: 'هوش سوخت',
    grossBurn30d: 'سوخت ناخالص (۳۰ روز)',
    netBurn30d: 'سوخت خالص (۳۰ روز)',
    burnMultiple: 'ضریب سوخت',
    avgBurn3m: 'میانگین سوخت ۳ ماهه',
    runwayCurrent: 'مدت دوام (فعلی)',
    forecast: 'پیش‌بینی',
    base: 'پایه',
    conservative: 'محافظه‌کارانه',
    aggressive: 'تهاجمی',
    addTransaction: 'افزودن تراکنش',
    addAccount: 'افزودن حساب',
    cashFlow: 'جریان نقدی',
    accountsAndActivity: 'حساب‌ها و فعالیت',
    recentTransactions: 'تراکنش‌های اخیر',
    noAccountsYet: 'هنوز حسابی اضافه نشده. یک حساب اضافه کنید.',
    noTransactionsYet: 'هنوز تراکنشی نیست. یکی اضافه کنید.',
    failedToLoad: 'بارگذاری داشبورد ناموفق بود.',
    apiUnreachable: 'احتمالاً API در دسترس نیست. بک‌اند روی پورت ۸۰۰۰ و CORS را بررسی کنید.',
    guestMode: 'حالت مهمان',
    guestModeDesc: 'برای اتصال حساب‌های واقعی و ردیابی هزینه‌ها ثبت‌نام کنید.',
    youAreIn: 'شما در ',
    youAreInSuffix: ' هستید.',
    sampleDashboard: 'نمای نمونه برای بازدید بدون ورود.',
    totalBalance: 'موجودی کل',
    incomeMonth: 'درآمد (ماه)',
    expensesMonth: 'هزینه‌ها (ماه)',
    netMonth: 'خالص (ماه)',
    acrossAccounts: 'حساب',
    thisMonthToDate: 'تا امروز این ماه',
    budgetsAndGoals: 'بودجه و هدف',
    cashflowSnapshot: 'نمای جریان نقدی',
    last30Days: '۳۰ روز گذشته',
    spendingByCategory: 'هزینه به‌تفکیک دسته',
    recentActivity: 'فعالیت اخیر',
    signInToTrack: 'وارد شوید تا تراکنش‌های واقعی را ببینید.',
    shareableLinkComing: 'لینک فقط‌خواندنی — به‌زودی',
    drillDown: 'جزئیات و تاریخچه.',
  },
  investors: {
    titleBefore: 'با اطمینان ',
    titleHighlight: 'ARR/MRR',
    titleAfter: ' را به سرمایه‌گذاران ارائه دهید.',
    title: 'با اطمینان ARR/MRR را به سرمایه‌گذاران ارائه دهید.',
    subtitle: 'ترکیب درآمد تکرارشونده و تغییرات در طول زمان.',
    cashRevenue: 'درآمد نقدی',
    accrualRevenue: 'درآمد تعهدی',
    mrrArr: 'MRR / ARR',
    mrrArrByCustomers: 'MRR / ARR به‌تفکیک مشتری',
    dateRange: 'بازه تاریخ',
    exportCsv: 'خروجی CSV',
    compositionTitle: 'ترکیب درآمد تکرارشونده و تغییرات در طول زمان',
    stripeDisclaimer: '(جدول بر اساس تاریخ شروع و پایان اشتراک در Stripe. تراکنش‌های بدون اشتراک لحاظ نشده‌اند)',
    customer: 'مشتری',
    beginningOfPeriod: 'ابتدای دوره',
    new: 'جدید',
    reactivation: 'بازفعال‌سازی',
    expansion: 'توسعه',
    contraction: 'کاهش',
    lost: 'از دست‌رفته',
    endOfPeriod: 'انتهای دوره',
    arrGrossChurnRate: 'نرخ ریزش ناخالص ARR',
    arrGrossRetentionRate: 'نرخ نگهداری ناخالص ARR',
    arrNetChurnRate: 'نرخ ریزش خالص ARR',
    keyMetrics: 'شاخص‌های کلیدی',
    mrrDef: 'MRR — درآمد ماهانه تکرارشونده',
    arrDef: 'ARR — درآمد سالانه تکرارشونده',
    churnDef: 'نرخ ریزش — درصد اشتراک‌های از دست‌رفته',
    retentionDef: 'نرخ نگهداری — درصد اشتراک‌های حفظ‌شده',
    viewReport: 'مشاهده گزارش ARR / MRR',
  },
  landing: {
    smartAccounting: 'نرم‌افزار حسابداری هوشمند',
    forStartups: 'برای استارتاپ‌ها.',
    tagline: 'هوش مالی لحظه‌ای. اول جریان نقدی — نه دفتر کل.',
    getStartedFree: 'شروع رایگان',
    goToDashboard: 'رفتن به داشبورد',
    getCashBurnRunway: 'داده‌های نقد، سوخت و مدت دوام را لحظه‌ای ببینید.',
    founderKpis: 'نمای کلی بنیانگذار با نوار شاخص، نمودار سوخت و موجودی نقد، هزینه و درآمد.',
    openDashboard: 'باز کردن داشبورد',
    confidentlyPresent: 'با اطمینان ARR/MRR را به سرمایه‌گذاران ارائه دهید.',
    compositionExport: 'ترکیب درآمد تکرارشونده، ریزش و نگهداری — خروجی CSV یا PDF.',
    footer: 'نکسوس — هوش مالی لحظه‌ای برای اپراتورهای استارتاپ.',
  },
  settings: {
    title: 'تنظیمات',
    loading: 'در حال بارگذاری…',
    guestMode: 'حالت مهمان',
    createAccountToManage: 'برای مدیریت تنظیمات پروفایل ثبت‌نام کنید.',
    profile: 'پروفایل',
    profileUpdated: 'پروفایل به‌روز شد.',
    saving: 'در حال ذخیره…',
    fullName: 'نام کامل',
    chooseTheme: 'روشن، تیره یا سیستم.',
    light: 'روشن',
    dark: 'تیره',
    system: 'سیستم',
    logout: 'خروج',
    failedToLoadUser: 'بارگذاری اطلاعات کاربر ناموفق بود.',
  },
  payments: {
    title: 'پرداخت‌ها',
    payWithZarinPal: 'پرداخت با زرین‌پال',
    zarinpalTitle: 'پرداخت‌ها (زرین‌پال)',
    amount: 'مبلغ',
    description: 'توضیح',
    backToDashboard: 'بازگشت به داشبورد',
  },
  budgets: {
    title: 'بودجه‌ها',
    createBudget: 'ایجاد بودجه',
    noBudgetsYet: 'هنوز بودجه‌ای نیست.',
    createBudgetDescription: 'بودجه بسازید تا هزینه را ردیابی کنید و با نزدیک شدن به سقف مطلع شوید.',
    editBudget: 'ویرایش بودجه',
    newBudget: 'بودجه جدید',
    budget: 'بودجه',
    spent: 'خرج‌شده',
    remaining: 'باقی‌مانده',
  },
  goals: {
    title: 'اهداف',
    createGoal: 'ایجاد هدف',
    noGoalsYet: 'هنوز هدفی نیست.',
    createGoalDescription: 'هدف پس‌انداز تعیین کنید و پیشرفت را ببینید.',
    editGoal: 'ویرایش هدف',
    newGoal: 'هدف جدید',
    percentComplete: '٪ تکمیل',
  },
  reports: {
    title: 'گزارش‌ها',
    expenses: 'هزینه‌ها',
    expensesByCategory: 'هزینه به‌تفکیک دسته',
    incomeVsExpenses: 'درآمد در برابر هزینه',
    income: 'درآمد',
    net: 'خالص',
    noExpenseData: 'داده‌ای برای هزینه موجود نیست.',
    exportTransactionsCsv: 'خروجی تراکنش‌ها (CSV)',
    exporting: 'در حال خروجی…',
  },
  recurring: {
    title: 'تراکنش‌های تکرارشونده',
    addRecurring: 'افزودن تکرارشونده',
    nextRunDate: 'تاریخ اجرای بعدی',
    scheduleDescription: 'درآمد یا هزینه دوره‌ای (مثلاً اجاره ماهانه، حقوق). تاریخ اجرا برای نمایش است.',
    noRecurringYet: 'هنوز تراکنش تکرارشونده‌ای نیست.',
    addOneAbove: 'یکی از بالا اضافه کنید.',
    addingRecurring: 'در حال افزودن…',
    backToDashboard: 'بازگشت به داشبورد',
    scheduled: 'زمان‌بندی‌شده',
    account: 'حساب',
    select: 'انتخاب',
    amount: 'مبلغ',
    type: 'نوع',
    frequency: 'دوره',
    expense: 'هزینه',
    income: 'درآمد',
    weekly: 'هفتگی',
    monthly: 'ماهانه',
    yearly: 'سالانه',
    descriptionOptional: 'توضیح (اختیاری)',
    remove: 'حذف',
    removeConfirm: 'این تراکنش تکرارشونده حذف شود؟',
  },
  connectBank: {
    title: 'اتصال بانک',
    addAccountManually: 'افزودن حساب دستی',
    backToDashboard: 'بازگشت به داشبورد',
  },
  empty: {
    noData: 'داده‌ای وجود ندارد.',
  },
  confirm: {
    areYouSure: 'مطمئن هستید؟',
    deleteTransaction: 'حذف تراکنش؟',
    deleteTransactionMessage: 'این تراکنش حذف می‌شود و موجودی حساب به‌روز می‌شود. این عمل قابل بازگشت نیست.',
    deleteBudget: 'حذف بودجه؟',
    deleteGoal: 'حذف هدف؟',
    deleteAccount: 'حذف حساب؟',
    deleteItemMessage: 'حذف می‌شود. این عمل قابل بازگشت نیست.',
    deleteAccountMessage: 'این حساب و تاریخچه تراکنش‌های آن تحت تأثیر قرار می‌گیرد. این عمل قابل بازگشت نیست.',
  },
  accounts: {
    title: 'حساب‌ها',
    addFirstDescription: 'اولین حساب خود را اضافه کنید تا موجودی و تراکنش‌ها را ردیابی کنید.',
    addAccount: 'افزودن حساب',
    editAccount: 'ویرایش حساب',
    newAccount: 'حساب جدید',
  },
  transactions: {
    title: 'تراکنش‌ها',
    addTransactionDesc: 'تراکنش اضافه کنید، از CSV وارد کنید یا در بانکی یک پیامک بانکی paste کنید.',
    addTransaction: 'افزودن تراکنش',
    importCsv: 'ورود CSV',
    noDescription: 'بدون توضیح',
    editTransaction: 'ویرایش تراکنش',
    newTransaction: 'تراکنش جدید',
  },
  bankingMessages: {
    savedMessages: 'پیام‌های ذخیره‌شده',
  },
  junior: {
    title: 'پس‌انداز هوشمند جونیور',
    subtitle: 'حساب‌های تحت کنترل والدین: پس‌انداز هدف‌محور، واریز خودکار، پاداش.',
    addChild: 'افزودن فرزند',
    addAChild: 'افزودن یک فرزند',
    name: 'نام',
    childName: 'نام فرزند',
    add: 'افزودن',
    adding: 'در حال افزودن…',
    noChildrenYet: 'هنوز فرزندی اضافه نشده.',
    addChildToStart: 'یک فرزند اضافه کنید تا شروع کنید.',
    viewGoalsDepositsRewards: 'اهداف، واریزها و پاداش‌ها',
    backToJuniorSavings: 'بازگشت به پس‌انداز جونیور',
    whyJunior: 'چرا پس‌انداز جونیور؟',
    why1: 'پس‌انداز هدف‌محور برای عادت از سنین پایین',
    why2: 'واریز خودکار (مقرری) که شما کنترل می‌کنید',
    why3: 'ردیابی پیشرفت و پاداش',
    why4: 'کنترل والدین: شما اهداف را تأیید و مبالغ را تعیین می‌کنید',
    goals: 'اهداف',
    noGoalsYet: 'هنوز هدفی نیست.',
    createGoal: 'ایجاد هدف',
    goalName: 'نام هدف',
    targetAmount: 'مبلغ هدف',
    targetDate: 'تاریخ هدف (اختیاری)',
    approveGoal: 'تأیید هدف',
    automatedDeposits: 'واریزهای خودکار',
    noDepositsYet: 'واریز زمان‌بندی‌شده‌ای نیست.',
    createDeposit: 'افزودن واریز خودکار',
    sourceAccount: 'حساب مبدأ',
    nextRunDate: 'تاریخ اجرای بعدی',
    nextRun: 'اجرای بعدی',
    rewards: 'پاداش‌ها',
    noRewardsYet: 'هنوز پاداشی نیست.',
    addReward: 'ثبت پاداش',
    rewardType: 'نوع پاداش',
    financialEducation: 'آموزش مالی',
    saveFirstTip: 'اول پس‌انداز کنید. کمی کنار بگذارید قبل از خرج کردن.',
    goalsHelp: 'اهداف کمک می‌کنند. پس‌انداز برای چیزی که می‌خواهید راحت‌تر است.',
    smallStepsCount: 'قدم‌های کوچک مهم‌اند. کمی هر هفته جمع می‌شود.',
    saved: 'ذخیره‌شده',
    failedToLoad: 'بارگذاری ناموفق',
    notFound: 'یافت نشد',
    weekly: 'هفتگی',
    biweekly: 'دو هفته‌ای',
    monthly: 'ماهانه',
    milestone: 'میلستون',
    bonus: 'پاداش',
    custom: 'سفارشی',
  },
} as const

export type FaKeys = typeof fa

/** Get nested value by path like 'common.signIn' */
export function t(path: string): string {
  const keys = path.split('.')
  let obj: unknown = fa
  for (const k of keys) {
    if (obj && typeof obj === 'object' && k in obj) obj = (obj as Record<string, unknown>)[k]
    else return path
  }
  return typeof obj === 'string' ? obj : path
}
